import { Search, FileText, Workflow, Shield, Database, GitBranch, Sparkles, LucideIcon } from "lucide-react";

export type SearchResultType = string;

export const typeIcons: Record<SearchResultType, LucideIcon> = {
  workflow: Workflow,
  "workflow-template": Workflow,
  "workflow-node": Workflow,
  compliance: Shield,
  "compliance-control": Shield,
  evidence: FileText,
  cmdb: Database,
  knowledge: FileText,
  change: GitBranch,
  "change-schedule": GitBranch,
  project: GitBranch,
  vendor: FileText,
  budget: FileText,
  incident: Shield,
  "service-request": FileText,
  lead: FileText,
  opportunity: FileText,
  quote: FileText,
  "purchase-order": FileText,
  invoice: FileText,
  expense: FileText,
  "employee-onboarding": FileText,
  contract: FileText,
  "config-item": Database,
  "cipp-policy": Shield,
  product: FileText,
  "customer-account": FileText,
  page: Sparkles,
  anomaly: Shield,
  audit: Shield,
  user: FileText,
  application: FileText,
  tenant: Database,
  onboarding: FileText,
  framework: Shield,
  "ai-chat": Sparkles,
  risk: Shield,
  remediation: Shield,
  sla: FileText,
  department: FileText,
  employee: FileText,
  "time-entry": FileText,
  "leave-request": FileText,
  warehouse: Database,
  inventory: Database,
  "network-device": Database,
  "mcp-server": Database,
  "prompt-template": Sparkles,
  role: Shield,
  "asset-financial": FileText,
  "automation-suggestion": Sparkles,
  "ci-relationship": GitBranch,
  "audit-entry": Shield,
  "workflow-step": Workflow,
  "mcp-log": Database,
};

export const typeLabels: Record<SearchResultType, string> = {
  workflow: "Workflow",
  "workflow-template": "Workflow Template",
  "workflow-node": "Workflow Node",
  compliance: "Compliance",
  "compliance-control": "Compliance Control",
  evidence: "Evidence",
  cmdb: "CMDB",
  knowledge: "Knowledge",
  change: "Change Request",
  "change-schedule": "Maintenance Schedule",
  project: "Project",
  vendor: "Vendor",
  budget: "Budget",
  incident: "Incident",
  "service-request": "Service Request",
  lead: "Lead",
  opportunity: "Opportunity",
  quote: "Quote",
  "purchase-order": "Purchase Order",
  invoice: "Invoice",
  expense: "Expense",
  "employee-onboarding": "Employee Onboarding",
  contract: "Contract",
  "config-item": "Configuration Item",
  "cipp-policy": "CIPP Policy",
  product: "Product",
  "customer-account": "Customer Account",
  page: "Page",
  anomaly: "Anomaly",
  audit: "Audit Log",
  user: "User",
  application: "Application",
  tenant: "Tenant",
  onboarding: "Client Onboarding",
  framework: "Framework",
  "ai-chat": "AI Chat",
  risk: "Risk Assessment",
  remediation: "Remediation Rule",
  sla: "SLA",
  department: "Department",
  employee: "Employee",
  "time-entry": "Time Entry",
  "leave-request": "Leave Request",
  warehouse: "Warehouse",
  inventory: "Inventory",
  "network-device": "Network Device",
  "mcp-server": "MCP Server",
  "prompt-template": "Prompt Template",
  role: "Role",
  "asset-financial": "Asset Financial",
  "automation-suggestion": "Automation",
  "ci-relationship": "CI Relationship",
  "audit-entry": "Audit Entry",
  "workflow-step": "Workflow Step",
  "mcp-log": "MCP Log",
};

export interface SearchResult {
  type: string;
  title: string;
  url: string;
  data: any;
  description?: string;
}

export interface SearchResponse {
  results: SearchResult[];
  aiSummary?: string;
  topMatch?: string;
  devMode?: boolean;
  userRoles?: string[];
}
