import { supabase } from '@/integrations/supabase/client';
import { Database } from '@/integrations/supabase/types';
import { CreateVendorInput, Vendor } from '@/types/vendor';

/**
 * Vendor Service
 * Centralizes all vendor-related database operations
 */

// Vendor types
type VendorInsert = Database['public']['Tables']['documentation_vendors']['Insert'];
type VendorUpdate = Database['public']['Tables']['documentation_vendors']['Update'];
type VendorRow = Database['public']['Tables']['documentation_vendors']['Row'];
type VendorContract = Database['public']['Tables']['vendor_contracts']['Row'];
type VendorContractInsert = Database['public']['Tables']['vendor_contracts']['Insert'];
type VendorPerformance = Database['public']['Tables']['vendor_performance']['Row'];
type VendorPerformanceInsert = Database['public']['Tables']['vendor_performance']['Insert'];

/**
 * Vendor Service
 */
export class VendorService {
  static async createVendor(input: CreateVendorInput, customerId: string, userId: string): Promise<Vendor> {
    const vendorInput: VendorInsert = {
      ...input,
      customer_id: customerId,
      created_by: userId,
      vendor_code: '', // Will be auto-generated by trigger
    };

    const { data, error } = await supabase
      .from('documentation_vendors')
      .insert([vendorInput])
      .select()
      .maybeSingle();

    if (error) throw new Error(`Failed to create vendor: ${error.message}`);
    if (!data) throw new Error('Failed to create vendor: No data returned');
    
    return data as Vendor;
  }

  static async getActiveVendors(customerId: string): Promise<Vendor[]> {
    const { data, error } = await supabase
      .from('documentation_vendors')
      .select('*')
      .eq('customer_id', customerId)
      .eq('status', 'active')
      .order('vendor_name', { ascending: true });

    if (error) throw new Error(`Failed to fetch active vendors: ${error.message}`);
    return data as Vendor[];
  }

  static async updateVendor(id: string, updates: VendorUpdate) {
    const { data, error } = await supabase
      .from('documentation_vendors')
      .update(updates)
      .eq('id', id)
      .select()
      .maybeSingle();

    if (error) throw new Error(`Failed to update vendor: ${error.message}`);
    if (!data) throw new Error('Vendor not found');
    
    return data as VendorRow;
  }

  static async deleteVendor(id: string) {
    const { error } = await supabase
      .from('documentation_vendors')
      .delete()
      .eq('id', id);

    if (error) throw new Error(`Failed to delete vendor: ${error.message}`);
  }

  static async getVendorsByCustomer(customerId: string) {
    const { data, error } = await supabase
      .from('documentation_vendors')
      .select('*')
      .eq('customer_id', customerId)
      .order('vendor_name', { ascending: true });

    if (error) throw new Error(`Failed to fetch vendors: ${error.message}`);
    return data as VendorRow[];
  }

  static async getVendorById(id: string) {
    const { data, error } = await supabase
      .from('documentation_vendors')
      .select('*')
      .eq('id', id)
      .maybeSingle();

    if (error) throw new Error(`Failed to fetch vendor: ${error.message}`);
    return data as VendorRow | null;
  }

  // Vendor Contracts Methods

  /**
   * Create a new vendor contract
   */
  static async createContract(input: VendorContractInsert): Promise<VendorContract> {
    const { data, error } = await supabase
      .from('vendor_contracts')
      .insert(input)
      .select()
      .maybeSingle();

    if (error) throw new Error(`Failed to create contract: ${error.message}`);
    if (!data) throw new Error('No data returned after creating contract');

    return data;
  }

  /**
   * Get all contracts for a vendor
   */
  static async getContractsByVendor(vendorId: string, customerId: string): Promise<VendorContract[]> {
    const { data, error } = await supabase
      .from('vendor_contracts')
      .select('*')
      .eq('vendor_id', vendorId)
      .eq('customer_id', customerId)
      .order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to fetch contracts: ${error.message}`);
    return data || [];
  }

  // Vendor Performance Methods

  /**
   * Create a vendor performance evaluation
   */
  static async createPerformanceEvaluation(input: VendorPerformanceInsert): Promise<VendorPerformance> {
    const { data, error } = await supabase
      .from('vendor_performance')
      .insert(input)
      .select()
      .maybeSingle();

    if (error) throw new Error(`Failed to create performance evaluation: ${error.message}`);
    if (!data) throw new Error('No data returned after creating evaluation');

    return data;
  }

  /**
   * Get all performance evaluations for a vendor
   */
  static async getPerformanceByVendor(vendorId: string, customerId: string): Promise<VendorPerformance[]> {
    const { data, error } = await supabase
      .from('vendor_performance')
      .select('*')
      .eq('vendor_id', vendorId)
      .eq('customer_id', customerId)
      .order('evaluation_date', { ascending: false });

    if (error) throw new Error(`Failed to fetch performance evaluations: ${error.message}`);
    return data || [];
  }
}
