-- =============================================
-- AUTONOMOUS AI AGENT INFRASTRUCTURE
-- =============================================

-- Agent State Management
CREATE TABLE IF NOT EXISTS ai_agent_state (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  department TEXT NOT NULL,
  agent_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'error', 'maintenance')),
  current_task TEXT,
  last_action_at TIMESTAMPTZ DEFAULT now(),
  next_scheduled_action TIMESTAMPTZ,
  metrics JSONB DEFAULT '{}'::jsonb,
  configuration JSONB DEFAULT '{}'::jsonb,
  error_count INTEGER DEFAULT 0,
  success_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(customer_id, department)
);

-- Agent Persistent Memory
CREATE TABLE IF NOT EXISTS ai_agent_memory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  department TEXT NOT NULL,
  memory_type TEXT NOT NULL CHECK (memory_type IN ('conversation', 'observation', 'decision', 'learning', 'context')),
  memory_key TEXT NOT NULL,
  memory_value JSONB NOT NULL,
  importance_score INTEGER DEFAULT 5 CHECK (importance_score BETWEEN 1 AND 10),
  access_count INTEGER DEFAULT 0,
  last_accessed_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_agent_memory_lookup ON ai_agent_memory(customer_id, department, memory_type, memory_key);
CREATE INDEX idx_agent_memory_importance ON ai_agent_memory(customer_id, department, importance_score DESC);

-- Agent Autonomous Tasks
CREATE TABLE IF NOT EXISTS ai_agent_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  department TEXT NOT NULL,
  task_type TEXT NOT NULL CHECK (task_type IN ('monitor', 'alert', 'analyze', 'optimize', 'report', 'coordinate')),
  task_name TEXT NOT NULL,
  task_config JSONB NOT NULL,
  schedule_cron TEXT,
  is_active BOOLEAN DEFAULT true,
  last_executed_at TIMESTAMPTZ,
  next_execution_at TIMESTAMPTZ,
  execution_count INTEGER DEFAULT 0,
  success_count INTEGER DEFAULT 0,
  failure_count INTEGER DEFAULT 0,
  avg_execution_time_ms INTEGER,
  priority INTEGER DEFAULT 5 CHECK (priority BETWEEN 1 AND 10),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_agent_tasks_execution ON ai_agent_tasks(is_active, next_execution_at) WHERE is_active = true;

-- Agent Task Execution History
CREATE TABLE IF NOT EXISTS ai_agent_task_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES ai_agent_tasks(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL,
  department TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('success', 'failure', 'partial', 'skipped')),
  execution_time_ms INTEGER,
  results JSONB,
  error_message TEXT,
  actions_taken JSONB DEFAULT '[]'::jsonb,
  metrics_captured JSONB DEFAULT '{}'::jsonb,
  executed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_task_executions_lookup ON ai_agent_task_executions(task_id, executed_at DESC);

-- Proactive Alerts Generated by Agents
CREATE TABLE IF NOT EXISTS ai_agent_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  department TEXT NOT NULL,
  alert_type TEXT NOT NULL CHECK (alert_type IN ('anomaly', 'threshold', 'prediction', 'recommendation', 'urgent')),
  severity TEXT NOT NULL CHECK (severity IN ('info', 'warning', 'critical', 'emergency')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  detected_by_task_id UUID REFERENCES ai_agent_tasks(id),
  supporting_data JSONB,
  recommended_actions JSONB DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'acknowledged', 'investigating', 'resolved', 'dismissed')),
  acknowledged_by UUID,
  acknowledged_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_agent_alerts_active ON ai_agent_alerts(customer_id, department, status) WHERE status IN ('new', 'acknowledged');
CREATE INDEX idx_agent_alerts_severity ON ai_agent_alerts(customer_id, severity, created_at DESC);

-- Cross-Department Agent Coordination
CREATE TABLE IF NOT EXISTS agent_coordination_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  from_department TEXT NOT NULL,
  to_department TEXT NOT NULL,
  message_type TEXT NOT NULL CHECK (message_type IN ('request', 'response', 'notification', 'escalation')),
  subject TEXT NOT NULL,
  content JSONB NOT NULL,
  priority INTEGER DEFAULT 5 CHECK (priority BETWEEN 1 AND 10),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  response_data JSONB,
  parent_message_id UUID REFERENCES agent_coordination_messages(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ
);

CREATE INDEX idx_coordination_inbox ON agent_coordination_messages(customer_id, to_department, status, priority DESC);

-- Agent Learning Records
CREATE TABLE IF NOT EXISTS ai_agent_learning (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id UUID NOT NULL,
  department TEXT NOT NULL,
  learning_type TEXT NOT NULL CHECK (learning_type IN ('pattern', 'optimization', 'correction', 'feedback')),
  learned_from TEXT NOT NULL,
  lesson JSONB NOT NULL,
  confidence_score NUMERIC(3,2) CHECK (confidence_score BETWEEN 0 AND 1),
  applied_count INTEGER DEFAULT 0,
  success_rate NUMERIC(3,2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_applied_at TIMESTAMPTZ
);

CREATE INDEX idx_agent_learning_lookup ON ai_agent_learning(customer_id, department, learning_type, confidence_score DESC);

-- Enable RLS
ALTER TABLE ai_agent_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agent_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agent_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agent_task_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agent_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_coordination_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agent_learning ENABLE ROW LEVEL SECURITY;

-- RLS Policies for ai_agent_state
CREATE POLICY "Users can view agent state in their org"
  ON ai_agent_state FOR SELECT
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

CREATE POLICY "Admins can manage agent state"
  ON ai_agent_state FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies for ai_agent_memory
CREATE POLICY "Service role can manage agent memory"
  ON ai_agent_memory FOR ALL
  USING (true);

CREATE POLICY "Users can view agent memory in their org"
  ON ai_agent_memory FOR SELECT
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

-- RLS Policies for ai_agent_tasks
CREATE POLICY "Users can view agent tasks in their org"
  ON ai_agent_tasks FOR SELECT
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

CREATE POLICY "Admins can manage agent tasks"
  ON ai_agent_tasks FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies for ai_agent_task_executions
CREATE POLICY "Users can view task executions in their org"
  ON ai_agent_task_executions FOR SELECT
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

CREATE POLICY "Service role can insert task executions"
  ON ai_agent_task_executions FOR INSERT
  WITH CHECK (true);

-- RLS Policies for ai_agent_alerts
CREATE POLICY "Users can view alerts in their org"
  ON ai_agent_alerts FOR SELECT
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

CREATE POLICY "Users can acknowledge alerts in their org"
  ON ai_agent_alerts FOR UPDATE
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

CREATE POLICY "Service role can create alerts"
  ON ai_agent_alerts FOR INSERT
  WITH CHECK (true);

-- RLS Policies for agent_coordination_messages
CREATE POLICY "Users can view coordination messages in their org"
  ON agent_coordination_messages FOR SELECT
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

CREATE POLICY "Service role can manage coordination"
  ON agent_coordination_messages FOR ALL
  USING (true);

-- RLS Policies for ai_agent_learning
CREATE POLICY "Users can view agent learning in their org"
  ON ai_agent_learning FOR SELECT
  USING (customer_id IN (
    SELECT customer_id FROM user_profiles WHERE user_id = auth.uid()
  ));

CREATE POLICY "Service role can manage learning"
  ON ai_agent_learning FOR ALL
  USING (true);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_agent_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_agent_state_updated_at
  BEFORE UPDATE ON ai_agent_state
  FOR EACH ROW EXECUTE FUNCTION update_agent_updated_at();

CREATE TRIGGER update_agent_memory_updated_at
  BEFORE UPDATE ON ai_agent_memory
  FOR EACH ROW EXECUTE FUNCTION update_agent_updated_at();

CREATE TRIGGER update_agent_tasks_updated_at
  BEFORE UPDATE ON ai_agent_tasks
  FOR EACH ROW EXECUTE FUNCTION update_agent_updated_at();

CREATE TRIGGER update_agent_alerts_updated_at
  BEFORE UPDATE ON ai_agent_alerts
  FOR EACH ROW EXECUTE FUNCTION update_agent_updated_at();