-- Add related_change_id to change_request_dashboard view
DROP VIEW IF EXISTS change_request_dashboard;

CREATE VIEW change_request_dashboard AS
SELECT 
  cr.id,
  cr.customer_id,
  cr.change_type,
  cr.change_status,
  cr.priority,
  cr.risk_level,
  cr.change_number,
  cr.title,
  cr.description,
  cr.justification,
  cr.implementation_plan,
  cr.rollback_plan,
  cr.testing_plan,
  cr.business_impact,
  cr.technical_impact,
  cr.affected_services,
  cr.requested_by,
  up.full_name as requested_by_name,
  cr.assigned_to,
  cr.implemented_by,
  cr.approved_by,
  cr.requested_start_time,
  cr.requested_end_time,
  cr.scheduled_start_time,
  cr.scheduled_end_time,
  cr.actual_start_time,
  cr.actual_end_time,
  cr.created_at,
  cr.updated_at,
  cr.submitted_at,
  cr.approved_at,
  cr.completed_at,
  cr.completion_notes,
  cr.success_criteria,
  cr.implementation_notes,
  cr.emergency_justification,
  cr.compliance_tags,
  cr.requires_emergency_approval,
  cr.audit_trail,
  cr.workflow_id,
  cr.automation_enabled,
  cr.affected_ci_ids,
  cr.primary_ci_id,
  cr.estimated_downtime_minutes,
  cr.affected_users,
  cr.risk_score,
  cr.risk_factors,
  cr.similar_changes_success_rate,
  cr.ml_recommendation,
  cr.related_change_id,
  cia.business_impact_score,
  cia.success_probability,
  (SELECT COUNT(*) FROM change_approvals ca WHERE ca.change_request_id = cr.id AND ca.approval_status = 'pending') as pending_approvals,
  (SELECT COUNT(*) FROM change_approvals ca WHERE ca.change_request_id = cr.id AND ca.approval_status = 'approved') as approved_count,
  (SELECT COUNT(*) FROM change_approvals ca WHERE ca.change_request_id = cr.id) as total_approvals
FROM change_requests cr
LEFT JOIN user_profiles up ON up.user_id = cr.requested_by
LEFT JOIN change_impact_analysis cia ON cia.change_request_id = cr.id;